# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hjIlMvu2b-FCh6SRdrTaRsxjp6UW9-go
"""

print("hello world")



print("hello \n world")
print("hello shiv")

city = "jaipur"
print (type(city))

city = "j"
print (type(city))

address= """ plot no.
street name
colony"""

print(address)

address=''' shiv
singh
dewra'''

print(address)

##print saprate words
print("good","morinng")

#variable
age=20
print(type(age))

city="jaipur"
print(type(city))

address='''vaishali nagar
jaipur'''
print(address)

company = "regex"
year=2024
print("company name is ", company,"year is",year)

company="regex"
year=2012
print(f"company name is {company} year is {year}")

###string formate method
username="aman"
msg=f"hello user {username}"
print(msg)

username="aman"
msg=f"hello user {username}"

print(msg)

username="shiv"
msg=f"hello shiv {username}"

username="tushar"
msg=f"hello mr. {username}"
print(msg)

username="shiv"
msg=f"hello mr. {username}"
print(msg)

##formate method
print("company name is {} and year is {}".format("regex","2024"))
print("company nsme is {0}and year is {1}".format("regex","2024"))

