# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a0rb4yow9B0jWGNSwJWQ8DxJ4OhBhUkD
"""

## data type
x=10
print(id(x))

x=10
print(x ,id(x))
y=x
print("y :",id(y))



10/2

100//3

10%3

3*4/4-15

x=10
x//=5
print(x)

14 | 13

16 | 15

11>>1

11>>2

23//4

14<<4

14<<2

15>>3

"J" in "JAIPUR"

"j" in "JAIPUR"

"PURR" not in " JAIPUR"